### PR TITLE
Remove tumor restriction on valid samples

### PR DESCRIPTION
**Pull request by ingkebil**
title says it all :)

A valid sample is now also a tumor sample.

What does this affect?
Valid samples will be eligible for delivery, now tumor samples' fastq files are not automatically linked.

### CODE REVIEW

**Comment by emiliaol** [comment]
So if I read this correct analysis in MIP will be possible for tumor samples? Which we do not want... or will the analysis be handled else where? And how will it affect a case with a tumor/normal pair where only the normal should be automatically included in the analysis in MIP?

**Comment by ingkebil** [comment]
No, this is only for delivery, not analysis.

**Comment by ingkebil** [comment]
Should we merge this?

**Comment by ingkebil** [comment]
Not needed. Closing.

**Pull request closed without merging**
