### PR TITLE
added EXL to PANELS

### PR DESCRIPTION
**Pull request by emiliaol**

### CODE REVIEW

**Comment by emiliaol** [comment]
We have a new version of the exome tag. Is there anywhere else it needs to be changed?

**Comment by emmser** [comment]
I think this is enough, or @ingkebil?

**Comment by ingkebil** [comment]
Yes! Looks good. This should be the only place.

What was the script of package you had troubles with when you xam back in January @emmser?

**Comment by ingkebil** [comment]
Aha, I remember! This is the only place deployment, unfortunately, needs to happen in two places: prod and "deliver"

**Comment by ingkebil** [comment]
Fixed in #17

**Pull request closed without merging**
